# permissions to do viewer scvs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: scv-viewer-role
rules:
- apiGroups:
  - core.run-linux.com
  resources:
  - scvs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - core.run-linux.com
  resources:
  - scvs/status
  verbs:
  - get
