apiVersion: v1
kind: Namespace
metadata:
  name: scv
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: scv-cr
rules:
  - apiGroups:
      - "core.run-linux.com"
    resources:
      - scv
    verbs:
      - delete
      - get
      - list
      - watch
      - update
      - patch
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: scv-sa
  namespace: scv
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: scv-crb
  namespace: scv
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: scv-cr
subjects:
  - kind: ServiceAccount
    name: scv-sa
    namespace: scv
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: scv
  namespace: scv
  labels:
    app: scv
spec:
  selector:
    matchLabels:
      app: scv
  template:
    metadata:
      labels:
        app: scv
    spec:
      serviceAccountName: scv-sa
      containers:
        - name: scv
          image: registry.cn-hangzhou.aliyuncs.com/geekcloud/scv
          imagePullPolicy: Always
          env:
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: NVIDIA_VISIBLE_DEVICES
              value: "all"
            - name: MODE
              value: "Full"
          resources:
            limits:
              memory: 200Mi
            requests:
              cpu: 100m
              memory: 200Mi
      terminationGracePeriodSeconds: 30